### ISSUE TITLE
Option for generating functional/stateless components

### ISSUE THREAD

**Issue by robertcoopercode** [Osedea/ignite-osd-generators#3]
When running `ignite g component ExampleComponent`, there should be an option to make the component "dumb", i.e. make the component a function rather than a class.

**Comment by adrienthiery** [comment]
@robertcoopercode : Dumb components are not always Stateless components.

So if you generate a component that is not connected to redux, that is a dumb component.

But indeed it would be nice to have an option to create a functional component.

I changed the title of the issue accordingly

**Comment by nathanielram** [comment]
Could also have the option to create a PureComponent?

**Comment by robertcoopercode** [comment]
What I meant was a Pure Component.

i.e.

```
const SampleComponent = (props: Props) => (
	<div>
		<p>Sup</p>
	</div>
)
```

**Comment by adrienthiery** [comment]
@robertcoopercode Do you mean : https://reactjs.org/docs/react-api.html#reactpurecomponent ?

**Comment by nathanielram** [comment]
I'm super confused about what's going on here.

Vocabulary:
https://stackoverflow.com/questions/40703675/react-functional-stateless-component-purecomponent-component-what-are-the-dif
