### ISSUE TITLE
List property in reducers should be an empty array instead of an empty object

### ISSUE THREAD

**Issue by robertcoopercode** [Osedea/ignite-osd-generators#5]
https://github.com/Osedea/ignite-osd-generators/blob/9dc4079f17721473b2ebac9634ac0372588ca35e/templates/service/reducer.js.ejs#L10

Instead of

```js
const initialState = fromJS({
    list: {},
    fetching: false,
    errors: null,
});
```

It should be 

```js
const initialState = fromJS({
    list: [],
    fetching: false,
    errors: null,
});
```

**Comment by evang9410** [comment]
we declare `list` as an empty object because usually with `immutable` we'll use an immutable `List` or `Map` which are `Collections` of immutable js
